(function(){var d=function(c){return""===c||null===c||void 0===c?!1:!0},h=function(c){var a=1E3;c&&(a=c);return(new Date).getTime().toString(16)+Math.floor(a*Math.random()).toString(16)},g=function(c,a,f,b,l,w,A,D,E){var F=encodeURIComponent(location.href);l="";0!=document.referrer.length&&(l=encodeURIComponent(document.referrer));a="https://t.felmat.net/jsonp/fmdl-callback?fmak="+a+"&fmcs="+f+"&dm="+c+"&i="+b+"&fc="+w+"&fp="+A+"&fb="+D+"&wnfaid="+E+"&target="+F+"&ref="+l+"&format_type=json&callback=fmdlcallback";
c=document.createElement("script");c.type="text/javascript";c.src=a;c.async=!0;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a)},e=function(c,a){return d(c[a])?c[a]:""},v=function(c,a,f){if(!d(a))return"";try{localStorage.setItem(c,JSON.stringify({v:a,t:f}))}catch(b){return""}},x=function(c){try{var a=JSON.parse(localStorage.getItem(c)),f=new Date(a.t);return(new Date).getTime()<=f.getTime()?a.v:""}catch(b){return""}},y=function(c,a){var f=[];try{var b=c.split(".");for(c=
0;c<b.length;c++){var l=b[c];if(l.length>a){var w=l.replace(/1/g,"o").replace(/3/g,"t").replace(/5/g,"f").replace(/7/g,"s").replace(/9/g,"n");f.push(w)}}return f.join("")}catch(A){return""}},n=function(){for(var c=[],a=document.cookie.split(";"),f=0;f<a.length;f++){var b=a[f];b=b.replace(/^\s+|\s+$/g,"");var l=b.indexOf("="),w=b.substring(0,l);b=unescape(b.slice(l+1));0===w.indexOf("_")&&(c[w]=b)}return c}(),p=function(c){c=[];var a=location.search.substring(1).split("&");a=a.filter(l=>l);for(var f=
0;a[f];f++){var b=a[f].split("=");d(b[1])&&("fmcs"==b[0]?c.fmcs=b[1]:"fmak"==b[0]||"rdk"==b[0]?c.fmak=b[1]:0===b[1].indexOf("fm.")?c.fmcs_ex=b[1]:"fbclid"==b[0]?c.fbclid=b[1]:"wnfaid"==b[0]&&(c.wnfaid=b[1]))}if(0!=document.referrer.length&&(a=document.referrer.split("#")[0].split("?"),1<a.length))for(a=a[1].split("&"),f=0;a[f];f++)b=a[f].split("="),d(b[1])&&("fmcs"==b[0]?c.fmcs=b[1]:"fmak"==b[0]||"rdk"==b[0]?c.fmak=b[1]:0===b[1].indexOf("fm.")?c.fmcs_ex=b[1]:"fbclid"==b[0]&&(c.fbclid=b[1]));return c}(),
q=function(){var c=[],a=document.domain.split(".");c.push(document.domain);if(3==a.length)"jp"==a[2]&&("co"==a[1]||"ne"==a[1]||"or"==a[1]||"ac"==a[1]||"go"==a[1]||"ad"==a[1]||"gr"==a[1]||"ed"==a[1]||"lg"==a[1]||"tokyo"==a[1])||"com"==a[2]&&"jpn"==a[1]||"net"==a[2]&&"jp"==a[1]||c.push(a[1]+"."+a[2]);else if(4<=a.length){var f=a.length-1,b=a.length-2,l=a.length-3;"jp"==a[f]&&("co"==a[b]||"ne"==a[b]||"or"==a[b]||"ac"==a[b]||"go"==a[b]||"ad"==a[b]||"gr"==a[b]||"ed"==a[b]||"lg"==a[b]||"tokyo"==a[b])||
"com"==a[f]&&"jpn"==a[b]||"net"==a[f]&&"jp"==a[b]?c.push(a[l]+"."+a[b]+"."+a[f]):c.push(a[b]+"."+a[f])}return c}(),t=function(c){var a=new Date,f=90;c&&(f=c);a.setTime(a.getTime()+864E5*f);return a.toUTCString()}(),u=e(n,"_fmitp"),z=x("_FmLss_");d(u)||(u=d(z)?z:h(1E11));h=e(n,"_fmtm");d(h)?h++:h=1;var k=e(p,"fmcs"),r=e(n,"_fmcs");x=x("_FmLscs_");var B=e(p,"fmcs_ex"),G=e(n,"_fbc"),H=e(n,"_fbp"),I=e(p,"fbclid"),m=e(n,"_ga"),C=e(n,"_gid");d(k)||(d(r)?k=r:d(x)?k=x:d(B)&&(k=B));n="";d(m)&&(n=d(C)?y(C,
5)+"-"+y(m,5):y(m,5));y=e(p,"fmak");e=e(p,"wnfaid");p="";0!=document.referrer.length&&(p=encodeURIComponent(document.referrer));r="https:"==location.protocol?"; SameSite=None; Secure":"";for(m=0;q[m];m++)if(0==m&&(d(k)&&(document.cookie="_fmcs="+k+"; path=/; expires="+t+r),document.cookie="_fmitp="+u+"; path=/; expires="+t+r),0<m||1==q.length)d(k)&&(document.cookie="_fmcs="+k+"; path=/; domain="+q[m]+"; expires="+t+r),document.cookie="_fmitp="+u+"; path=/; domain="+q[m]+"; expires="+t+r,document.cookie=
"_fmtm="+h+"; path=/; domain="+q[m]+"; max-age=60"+r,d(r)&&(d(k)&&(document.cookie="_fmrecs="+k+"; path=/; domain="+q[m]+"; expires="+t),document.cookie="_fmreitp="+u+"; path=/; domain="+q[m]+"; expires="+t);d(z)||v("_FmLss_",u,t);d(x)||v("_FmLscs_",k,t);if(5>=h)if(d(y))g(q,y,k,u,p,G,H,I,e);else if(d(k)||d(p))v="https://t.felmat.net/fmitp?i="+u+"&cs="+k+"&dm="+q+"&g="+n+"&ref="+p,g=document.createElement("script"),g.type="text/javascript",g.src=v+"&js=ON&t=1",g.async=!0,v=document.getElementsByTagName("script")[0],
v.parentNode.insertBefore(g,v)})();
var issetCallback=function(d){return""===d||null===d||void 0===d?!1:!0},setLocalStrageItemCallback=function(d,h,g){try{localStorage.setItem(d,JSON.stringify({v:h,t:g}))}catch(e){return""}},fmdlcallback=function(d){if(d)if(2==d.status)console.log(d.error);else{var h="fm."+d.uuid,g=d.domain,e=d.itp_id;d=d.referer;0!=d&&(d=encodeURIComponent(d));d="https://t.felmat.net/fmitp?i="+e+"&cs="+h+"&dm="+g+"&ref="+d;e=document.createElement("script");e.type="text/javascript";e.src=d+"&js=ON&t=2";e.async=!0;
d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(e,d);e=new Date;e.setTime(e.getTime()+7776E6);e=e.toUTCString();d="https:"==location.protocol?"; SameSite=None; Secure":"";dm_ary=g.split(",");for(g=0;dm_ary[g];g++)if(0==g&&(document.cookie="_fmcs="+h+"; path=/; expires="+e+d),0<g||1==dm_ary.length)document.cookie="_fmcs="+h+"; path=/; domain="+dm_ary[g]+"; expires="+e+d,d&&(document.cookie="_fmrecs="+h+"; path=/; domain="+dm_ary[g]+"; expires="+e);setLocalStrageItemCallback("_FmLscs_",
h,e)}};